[package]
name = "sheldon"
version = "0.5.4"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
description = "Fast, configurable, shell plugin manager."
documentation = "https://rossmacarthur.github.io/sheldon"
readme = "README.md"
homepage = "https://github.com/rossmacarthur/sheldon"
repository = "https://github.com/rossmacarthur/sheldon"
license = "MIT OR Apache-2.0"
keywords = ["shell", "plugin", "manager", "zsh", "bash"]
categories = ["command-line-utilities"]
build = "build.rs"
include = ["src/**/*", "LICENSE-*", "README.md", "build.rs"]

[dependencies]
ansi_term = "0.11.0"
anyhow = "1.0.32"
casual = "0.1.2"
fs2 = "0.4.3"
git2 = "0.13.8"
globwalk = "0.8.0"
handlebars = "3.4.0"
home = "0.5.3"
indexmap = { version = "1.5.1", features = ["serde-1", "rayon"] }
itertools = "0.9.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
rayon = "1.3.1"
regex = "1.3.9"
reqwest = { version = "0.10.7", features = ["blocking"] }
serde = { version = "1.0.115", features = ["derive"] }
structopt = "0.3.16"
thiserror = "1.0.20"
toml = { version = "0.5.6", features = ["preserve_order"] }
toml_edit = "0.2.0"
url = { version = "2.1.1", features = ["serde"] }
walkdir = "2.3.1"
which = { version = "4.0.2", default-features = false }

[dev-dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
pretty_assertions = "0.6.1"
tempfile = "3.1.0"

[workspace]
members = ["tools/generate-readme"]
